(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import Main.
Require Import MainRef.
Require Import Coq.ZArith.ZArith.
Local Open Scope Primitives_scope.

Lemma ref_incr_equiv_check : forall (x : i32),
  Main.ref_incr x = MainRef.ref_incr x.
Proof.
  intros x.
  unfold Main.ref_incr.
  unfold MainRef.ref_incr.
  reflexivity.
Qed.
