(** EquivCheck.v Autogenerated by REM-verification **)
Require Import Primitives.
Import Primitives.
Require Import SampleProject.
Require Import SampleProjectRef.
Require Import Coq.ZArith.ZArith.
Local Open Scope Primitives_scope.

Lemma ref_incr_equiv_check : forall (x : i32),
  SampleProject.ref_incr x = SampleProjectRef.ref_incr x.
Proof.
  intros x.
  unfold SampleProject.ref_incr.
  unfold SampleProjectRef.ref_incr.
  reflexivity.
Qed.
