[package]
name = "verifyer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
config = "0.15.7"
flexi_logger = "0.29.8"
log = "0.4.25"
rem-utils = "0.1.5"
serde = { version = "1.0.217", features = ["derive", "serde_derive"] }
