[programs]
aeneas = "/home/matt/rem-matt/rem-verification/programs/aeneas"
primitives = "/home/matt/rem-matt/rem-verification/verifyer/src/Primitives.v"


[coq]
original = "/home/matt/rem-matt/rem-verification/coq/SampleProject.v"
refactored = "/home/matt/rem-matt/rem-verification/coq/SampleProjectRef.v"

[llbc]
original = "/home/matt/rem-matt/rem-verification/llbc/sample_project.llbc"
refactored = "/home/matt/rem-matt/rem-verification/llbc/sample_project_ref.llbc"