(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [sample_crate] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module SampleCrate.

(** [sample_crate::ref_incr]:
    Source: 'src/main.rs', lines 5:0-7:1 *)
Definition ref_incr (x : i32) : result i32 :=
  i32_add x 1%i32.

(** [sample_crate::test_incr]:
    Source: 'src/main.rs', lines 8:0-12:1 *)
Definition test_incr : result unit :=
  y <- ref_incr 0%i32; massert (y s= 1%i32)
.

(** [sample_crate::main]:
    Source: 'src/main.rs', lines 1:0-3:1 *)
Definition main : result unit :=
  test_incr.

End SampleCrate.